---
version: 3
includes:
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/git.yaml

vars:
  BRANCH:
    sh: if [ $(git rev-parse --abbrev-ref HEAD) != "main" ]; then echo $(git rev-parse --abbrev-ref HEAD); else echo main ; fi
  MOLECULE_SCENARIO: docker_test

# PRECONDITION TO CHECK IF THE VIRTUAL ENVIRONMENT IS ACTIVATED
venv-precondition: &venv
  - sh: |
      pip -V | grep '.venv' >/dev/null 2>&1
    msg: "The pip version output does not contain .venv, Halting. Run task setup-venv, source .venv/bin/activate & task setup-molecule to proceed"

tasks:
  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | \
          sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"

  run-molecule:
    preconditions: *venv
    cmds:
      - molecule test -s {{ .MOLECULE_SCENARIO }}

  setup-molecule:
    preconditions: *venv
    cmds:
      - pip install -r molecule-requirements.txt
      - molecule --version

  setup-venv:
    desc: "Setup python virtual environment"
    cmds:
      - rm -rf ./.venv
      - python3 -m venv ./.venv
      - echo "DON'T FORGET TO RUN - source ./.venv/bin/activate"
