---
- name: Install Docker
  ansible.builtin.package:
    name: "{{ specific_docker_package | default(docker_package) }}"
    state: "{{ docker_package_state }}"
  ignore_errors: true
  notify: restart docker
  when: ansible_os_family != 'Debian'

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ specific_docker_package | default(docker_package) }}"
    state: "{{ docker_package_state }}"
    force: yes
  ignore_errors: true
  notify: restart docker
  when: ansible_os_family == 'Debian'
  
- name: Ensure Docker is started and enabled at boot.
  ansible.builtin.service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Make docker.service.d directory
  ansible.builtin.file:
    path: /usr/lib/systemd/system/docker.service.d
    state: directory

- name: Set Docker mount flags
  ansible.builtin.copy:
    dest: /usr/lib/systemd/system/docker.service.d/mount_flags.conf
    content: |
      [Service]
      MountFlags=shared
  register: mount_flags_updated
  when: ansible_distribution== "CentOS" and ansible_distribution_major_version != "8"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  when: mount_flags_updated is changed

- name: Allow dockerroot group to access Docker daemon
  ansible.builtin.copy:
    content: '{ "group": "dockerroot" }'
    dest: /etc/docker/daemon.json
