---
- name: Download and install kind+kubectl
  ansible.builtin.include_role:
    name: download-install-binary

- name: Generate kind config
  ansible.builtin.template:
    src: kind.yaml.j2
    dest: "{{ kind_cluster_name }}.yaml"

- name: Permissions for kind
  ansible.builtin.file:
    path: /usr/bin/kind
    mode: '0755'

- name: Create kind cluster
  ansible.builtin.shell: |
    kind create cluster --config /home/{{ ansible_user }}/{{ kind_cluster_name }}.yaml --name {{ kind_cluster_name }}
    kind get clusters
    mkdir -p /home/{{ ansible_user }}/.kube/
    kind get kubeconfig --name {{ kind_cluster_name }} > /home/{{ ansible_user }}/.kube/config
  when: create_kind_cluster|bool

- name: Permissions for kubeconfig
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube/config
    mode: '0600'
    owner: "{{ ansible_user }}"	 # comment