---
- hosts: all #"{{ target_host }}"
  become: true
  become_method: sudo

  vars:
    docker_install_compose: true
    docker_version: '' # leave empty for latest version or set e.g. '=5:23.0.6-1~ubuntu.23.04~lunar'
    install_kind: true
    kind_version: 0.27.0
    kind_cluster_name: kind1
    kubectl_version: 1.32.3
    kind_api_port: 6443
    kind_server: 127.0.0.1
    create_kind_cluster: true
    helmfile_version: 0.171.0
    helm_version: 3.17.2
    k9s_version: 0.40.10
    count_worker_nodes: 3
    count_controlplane_nodes: 1
    disableDefaultCNI: true
    kubeProxyMode: "none"
    node_labels: "ingress-ready=true"
    enable_ingress_ports: true
    enable_host_paths: true

    bin:
      kubectl:
        bin_name: "kubectl"
        bin_version: "{{ kubectl_version }}"
        check_bin_version_before_installing: true
        source_url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
        bin_to_copy: "kubectl"
        to_remove: "kubectl"
        bin_dir: "/usr/local/bin"
        version_cmd: " version --client"
        target_version: "{{ kubectl_version }}"
      kind:
        bin_name: kind
        bin_version: "{{ kind_version }}"
        check_bin_version_before_installing: true
        source_url: "https://github.com/kubernetes-sigs/kind/releases/download/v{{ kind_version }}/kind-linux-amd64"
        bin_to_copy: kind-linux-amd64
        to_remove: ""
        bin_dir: "/usr/bin/kind"
        version_cmd: "version"
        target_version: "{{ kind_version }}"
      helmfile:
        bin_name: helmfile
        bin_version: "{{ helmfile_version }}"
        check_bin_version_before_installing: true
        source_url: "https://github.com/helmfile/helmfile/releases/download/v{{ helmfile_version }}/helmfile_{{ helmfile_version }}_linux_amd64.tar.gz"
        bin_to_copy: helmfile
        to_remove: "helmfile"
        bin_dir: "/usr/bin/helmfile"
        version_cmd: "version"
        target_version: "{{ helmfile_version }}"
      helm:
        bin_name: helm
        bin_version: "{{ helm_version }}"
        check_bin_version_before_installing: true
        source_url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
        bin_to_copy: "linux-amd64/helm"
        to_remove: "helm"
        bin_dir: "/usr/bin/helm"
        version_cmd: "version"
        target_version: "{{ helm_version }}"
      k9s:
        bin_name: k9s
        bin_version: "{{ k9s_version }}"
        check_bin_version_before_installing: true
        source_url: "https://github.com/derailed/k9s/releases/download/v{{ k9s_version }}/k9s_Linux_amd64.tar.gz"
        bin_to_copy: "k9s"
        to_remove: "k9s"
        bin_dir: "/usr/bin/k9s"
        version_cmd: "version"
        target_version: "{{ k9s_version }}"


  roles:
    - install-configure-docker
