---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-certs: True
    requirements-file: collections.yaml
    role-file: roles.yaml
    ignore-errors: False
    force: True

driver:
  name: docker
platforms:
  # - name: rocky9
  #   image: "geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux9}-ansible:latest"
  #   command: ${MOLECULE_DOCKER_COMMAND:-""}
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #   cgroupns_mode: host
  #   privileged: true
  #   pre_build_image: true
  - name: ubuntu24
    image: geerlingguy/docker-ubuntu2404-ansible@sha256:129f93fb11c00d2452f541fc926234a2ecf7957d7348fb07832bd0bf6973f503
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

verifier:
  name: ansible

scenario:
  name: docker_test
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
