---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-certs: True
    requirements-file: collections.yaml
    role-file: roles.yaml
    ignore-errors: True
    force: True

driver:
  name: docker
platforms:
  - name: rocky9
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux9}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: ubuntu24
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

verifier:
  name: ansible

scenario:
  name: docker_test
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
