---
name: Ansible lint
on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  Lint-Ansible:
    runs-on: ghr-install-configure-docker-sthings-cicd
    container:
      image: eu.gcr.io/stuttgart-things/sthings-ansible:9.3.0
      options: --user=root #65532
    environment: k8s
    continue-on-error: false
    steps:
      - run: |
          whoami
    
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          path: ''

      - run: |
          ansible-lint tests/kind.yaml

          
#      - uses: actions/upload-artifact@v3
#        with:
#          name: hugo-public
#          path: public

      - name: Fix permissions
        run: |
          chmod -c -R +rX "blog/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
