---
name: Ansible lint
on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  yaml-lint:
    name: Lint yaml files
    uses: stuttgart-things/stuttgart-things/.github/workflows/lint-yaml.yaml@main
    with:
      environment-name: k8s
      runs-on: ghr-install-configure-docker-sthings-cicd
      continue-error: true
      yamllint-version: 1
      lintprofile-path: .yamllint
      artifact-name: yaml-lint
