---
name: Ansible lint
on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'fix/**'
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  yaml-lint:
    name: Lint yaml files
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-yaml-lint.yaml@feature/add-homerun-task-go
    with:
      runs-on: ghr-install-configure-docker-skyami-cicd
      environment-name: k8s
      continue-error: true
      yamllint-version: 1
      lintprofile-path: .yamllint
      artifact-name: yaml-lint

  ansible-lint:
    name: Lint ansible code
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-ansible-lint.yaml@feature/add-homerun-task-go # ansible-lint-24.2.1
    with:
      runs-on: ghr-install-configure-docker-skyami-cicd
      environment-name: k8s
      continue-error: true
      ansible-image: ghcr.io/stuttgart-things/sthings-ansible:11.1.0
      playbook: tests/test.yml
    needs: yaml-lint

  # molecule-test:
  #   name: Test ansible code w/ molecule
  #   uses: stuttgart-things/github-workflow-templates/.github/workflows/call-moluecule-test.yaml@main # ansible-lint-24.2.1
  #   with:
  #     runs-on: docker
  #     environment-name: k8s
  #     scenario-names: "['docker_test']"
  #   needs: ansible-lint
